# Generated by Django 2.0.4 on 2018-04-21 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_auto_20180421_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskAllocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedOn', models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True)),
                ('startedOn', models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True)),
                ('finisedOn', models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True)),
                ('estimatedFinishDate', models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assignedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskallocate_assignedBy', to=settings.AUTH_USER_MODEL)),
                ('assignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='actualEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 1, 9, 41, 405437)),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='releasedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reportedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 22), null=True),
        ),
        migrations.AddField(
            model_name='taskallocate',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task'),
        ),
    ]
