# Generated by Django 2.0.4 on 2018-04-22 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180422_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 16, 17, 12, 527820)),
        ),
    ]
