# Generated by Django 2.0.4 on 2018-04-22 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180422_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_addedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 22, 19, 0, 7, 161681), null=True),
        ),
    ]
