# Generated by Django 2.0.4 on 2018-04-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180422_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actualEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 23, 22, 33, 9, 920477), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reportedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='assignedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='estimatedFinishDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='finisedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='startedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 23), null=True),
        ),
    ]
