# Generated by Django 2.0.4 on 2018-04-24 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20180423_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crnNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 22, 54, 31, 75106), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reportedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedEndDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='revisedStartDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='assignedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='estimatedFinishDate',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='finisedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='taskallocate',
            name='startedOn',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 24), null=True),
        ),
    ]
